services:
  shrimp-waf:
    image: anssi/fcsc2026-web-shrimp-waf:latest
    environment:
      - HOOS_CTF_EMAIL=${HOOS_CTF_EMAIL:-}
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
      - LANGUAGE=${LANGUAGE:-fr}
    labels:
      ho.ctf.cyrhades: "challenge"
    ports:
      - ${PORT}:80
